services:
  ollama:
    image: ollama/ollama:0.20.5
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ~/.ollama:/root/.ollama
    restart: unless-stopped

volumes:
  ollama_data:
