"""File writer tool used by the Report and Historical Agents."""

from __future__ import annotations

from pathlib import Path
from typing import Any


def write_feedback_report(content: str, output_path: str) -> str:
    """Write the feedback report to disk, creating directories as needed.

    An existing file at ``output_path`` will be overwritten.

    Parameters
    ----------
    content:
        The Markdown-formatted feedback report string.
    output_path:
        Destination file path (absolute or relative).

    Returns
    -------
    str
        The resolved absolute path of the written file.
    """
    dest = Path(output_path)
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(content, encoding="utf-8")
    return str(dest.resolve())


def write_analysis_report(
    past_reports: list[dict[str, Any]],
    progression_insights: str,
    student_id: str,
    output_path: str,
) -> str:
    """Generate and write a performance analysis report to disk.

    Produces a Markdown document summarising the student's historical score
    data and the LLM-generated progression insights.

    Parameters
    ----------
    past_reports:
        Chronologically ordered list of previous report dicts, each
        containing ``session_id``, ``timestamp``, ``total_score``, and
        ``grade``.
    progression_insights:
        Plain-text progression summary generated by the Historical Agent.
    student_id:
        The student's unique identifier.
    output_path:
        Destination file path (absolute or relative).

    Returns
    -------
    str
        The resolved absolute path of the written file.
    """
    lines: list[str] = [
        "# Performance Analysis Report",
        "",
        f"**Student ID:** {student_id or 'N/A'}",
        "",
        "## Historical Scores",
        "",
    ]

    if past_reports:
        lines += [
            "| Session | Timestamp | Score | Grade |",
            "|---------|-----------|-------|-------|",
        ]
        for r in past_reports:
            lines.append(
                f"| {r.get('session_id', '')} "
                f"| {r.get('timestamp', '')} "
                f"| {r.get('total_score', '')} "
                f"| {r.get('grade', '')} |"
            )
    else:
        lines.append("_No historical records found for this student._")

    if progression_insights:
        lines += [
            "",
            "## Progression Insights",
            "",
            progression_insights,
        ]

    content = "\n".join(lines) + "\n"
    dest = Path(output_path)
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(content, encoding="utf-8")
    return str(dest.resolve())


def write_marking_sheet(
    student_id: str,
    student_name: str,
    module: str,
    assignment: str,
    scored_criteria: list[dict[str, Any]],
    total_score: float,
    total_marks: int,
    grade: str,
    output_path: str,
) -> str:
    """Generate and write a marking sheet report to disk.

    Produces a Markdown table listing each criterion with its awarded score,
    maximum score, and justification, followed by the overall result.

    Parameters
    ----------
    student_id:
        The student's unique identifier.
    student_name:
        The student's full name (may be empty if not extracted).
    module:
        Module code / name from the rubric.
    assignment:
        Assignment title from the rubric.
    scored_criteria:
        Per-criterion dicts produced by the Analysis Agent.
    total_score:
        Aggregate numeric score.
    total_marks:
        Maximum marks available.
    grade:
        Letter grade (A–F).
    output_path:
        Destination file path (absolute or relative).

    Returns
    -------
    str
        The resolved absolute path of the written file.
    """
    lines: list[str] = [
        "# Marking Sheet",
        "",
        f"**Module:** {module}  ",
        f"**Assignment:** {assignment}  ",
        f"**Student ID:** {student_id or 'N/A'}  ",
    ]
    if student_name:
        lines.append(f"**Student Name:** {student_name}  ")
    lines += [
        "",
        "## Criterion Scores",
        "",
        "| Criterion | Score | Max Score | Justification |",
        "|-----------|-------|-----------|---------------|",
    ]

    for c in scored_criteria:
        justification = c.get("justification", "").replace("|", "\\|")
        lines.append(
            f"| {c.get('name', c.get('criterion_id', ''))} "
            f"| {c.get('score', 0)} "
            f"| {c.get('max_score', 0)} "
            f"| {justification} |"
        )

    percentage = (total_score / total_marks * 100) if total_marks > 0 else 0.0
    lines += [
        "",
        "## Overall Result",
        "",
        f"| Total Score | Max Marks | Percentage | Grade |",
        f"|-------------|-----------|------------|-------|",
        f"| {total_score} | {total_marks} | {percentage:.2f}% | {grade} |",
    ]

    content = "\n".join(lines) + "\n"
    dest = Path(output_path)
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(content, encoding="utf-8")
    return str(dest.resolve())

