"""File writer tool used by the Report and Historical Agents."""

from __future__ import annotations

from pathlib import Path
from typing import Any


_ASSIGNMENT_MISTAKE_LABELS = {
    "missing_answer": "Missing answer",
    "out_of_context": "Out of context",
}


def _write_markdown_file(content: str, output_path: str) -> str:
    """Write Markdown content to disk and return the resolved path."""
    destination_path = Path(output_path)
    destination_path.parent.mkdir(parents=True, exist_ok=True)
    try:
        destination_path.write_text(content, encoding="utf-8")
    except OSError as exc:
        raise RuntimeError(
            f"Failed to write report to '{destination_path}': {exc}"
        ) from exc
    return str(destination_path.resolve())


def _escape_markdown_table_cell(value: Any) -> str:
    """Normalize a value for safe insertion into a Markdown table cell."""
    text = str(value)
    text = " ".join(text.splitlines())
    text = " ".join(text.split())
    return text.replace("|", "\\|")


def _assignment_mistake_label(value: Any) -> str:
    """Return a user-facing assignment mistake label."""
    return _ASSIGNMENT_MISTAKE_LABELS.get(str(value).strip().lower(), "None")


def write_feedback_report(content: str, output_path: str) -> str:
    """Write the feedback report to disk, creating directories as needed.

    An existing file at ``output_path`` will be overwritten.

    Parameters
    ----------
    content:
        The Markdown-formatted feedback report string.
    output_path:
        Destination file path (absolute or relative).

    Returns
    -------
    str
        The resolved absolute path of the written file.
    """
    return _write_markdown_file(content, output_path)


def write_analysis_report(
    past_reports: list[dict[str, Any]],
    progression_insights: str,
    student_id: str,
    output_path: str,
) -> str:
    """Generate and write a performance analysis report to disk.

    Produces a Markdown document summarising the student's historical score
    data and the LLM-generated progression insights.

    Parameters
    ----------
    past_reports:
        Chronologically ordered list of previous report dicts, each
        containing ``session_id``, ``timestamp``, ``total_score``, and
        ``grade``.
    progression_insights:
        Plain-text progression summary generated by the Historical Agent.
    student_id:
        The student's unique identifier.
    output_path:
        Destination file path (absolute or relative).

    Returns
    -------
    str
        The resolved absolute path of the written file.
    """
    markdown_lines: list[str] = [
        "# Performance Analysis Report",
        "",
        f"**Student ID:** {student_id or 'N/A'}",
        "",
        "## Historical Scores",
        "",
    ]

    if past_reports:
        markdown_lines.extend(
            [
            "| Session | Timestamp | Score | Grade |",
            "|---------|-----------|-------|-------|",
            ]
        )
        for report in past_reports:
            markdown_lines.append(
                f"| {report.get('session_id', '')} "
                f"| {report.get('timestamp', '')} "
                f"| {report.get('total_score', '')} "
                f"| {report.get('grade', '')} |"
            )
    else:
        markdown_lines.append("_No historical records found for this student._")

    if progression_insights:
        markdown_lines.extend(["", "## Progression Insights", "", progression_insights])

    return _write_markdown_file("\n".join(markdown_lines) + "\n", output_path)


def write_marking_sheet(
    student_id: str,
    student_name: str,
    module: str,
    assignment: str,
    scored_criteria: list[dict[str, Any]],
    total_score: float,
    total_marks: int,
    grade: str,
    output_path: str,
) -> str:
    """Generate and write a marking sheet report to disk.

    Produces a Markdown table listing each criterion with its awarded score,
    maximum score, and justification, followed by the overall result.

    Parameters
    ----------
    student_id:
        The student's unique identifier.
    student_name:
        The student's full name (may be empty if not extracted).
    module:
        Module code / name from the rubric.
    assignment:
        Assignment title from the rubric.
    scored_criteria:
        Per-criterion dicts produced by the Analysis Agent.
    total_score:
        Aggregate numeric score.
    total_marks:
        Maximum marks available.
    grade:
        Letter grade (A–F).
    output_path:
        Destination file path (absolute or relative).

    Returns
    -------
    str
        The resolved absolute path of the written file.
    """
    markdown_lines: list[str] = [
        "# Marking Sheet",
        "",
        f"**Module:** {module}  ",
        f"**Assignment:** {assignment}  ",
        f"**Student ID:** {student_id or 'N/A'}  ",
    ]
    if student_name:
        markdown_lines.append(f"**Student Name:** {student_name}  ")
    markdown_lines.extend(
        [
        "",
        "## Criterion Scores",
        "",
        "| Criterion | Score | Max Score | Common Mistake | Justification |",
        "|-----------|-------|-----------|----------------|---------------|",
        ]
    )

    common_assignment_mistakes: list[str] = []
    for criterion in scored_criteria:
        criterion_name = _escape_markdown_table_cell(
            criterion.get("name", criterion.get("criterion_id", ""))
        )
        score = _escape_markdown_table_cell(criterion.get("score", 0))
        max_score = _escape_markdown_table_cell(criterion.get("max_score", 0))
        mistake_label = _assignment_mistake_label(
            criterion.get("assignment_mistake", "none")
        )
        if mistake_label != "None":
            common_assignment_mistakes.append(f"{criterion_name}: {mistake_label}")

        justification = _escape_markdown_table_cell(criterion.get("justification", ""))
        markdown_lines.append(
            f"| {criterion_name} "
            f"| {score} "
            f"| {max_score} "
            f"| {_escape_markdown_table_cell(mistake_label)} "
            f"| {justification} |"
        )

    percentage = (total_score / total_marks * 100) if total_marks > 0 else 0.0
    markdown_lines.extend(
        [
            "",
            "## Overall Result",
            "",
            "| Total Score | Max Marks | Percentage | Grade |",
            "|-------------|-----------|------------|-------|",
            (
                f"| {_escape_markdown_table_cell(total_score)} "
                f"| {_escape_markdown_table_cell(total_marks)} "
                f"| {_escape_markdown_table_cell(f'{percentage:.2f}%')} "
                f"| {_escape_markdown_table_cell(grade)} |"
            ),
            "",
            "## Common Assignment Mistakes",
            "",
        ]
    )
    if common_assignment_mistakes:
        markdown_lines.extend(f"- {item}" for item in common_assignment_mistakes)
    else:
        markdown_lines.append("- None identified.")

    return _write_markdown_file("\n".join(markdown_lines) + "\n", output_path)
